### PR TITLE
Bring the tutorial's dependencies to their more recent versions

### PR DESCRIPTION
**Pull request by alinpopa**

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks! Why is bs-fetch and others here?

**Comment by alinpopa** [comment]
@chenglou no particular reason, I've only used them to play around with a bit more advanced situations, and I thought it's a good idea to have them there as well. Also, I've updated as many dependencies as possible while I was there. If you don't agree with them, no problem, I can remove them and have only the essentials updated.

**Comment by chenglou** [comment]
Yeah let's keep only the essential for now and include whatever we need on-demand. Though I've already upgraded bs-platform and ReasonReact earlier...

**Comment by alinpopa** [comment]
Will open a new PR; closing this one for now.

**Pull request closed without merging**
